In [3]:
#3.1
#task 1

import numpy as np

zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [9]:
#task 2 - Shape of an array

array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
    print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



In [10]:
#task 2 - reshape of an array

import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
reshaped_array = array.reshape(3, 2) 
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


In [11]:
#3.2
#task 1 - Arrays with evenly Spaced values - arange

a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x)
print(list(x))

x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [12]:
#task 1 - Arrays with evenly Spaced values - linspace
print(np.linspace(1, 10))
print(np.linspace(1, 10, 7))
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [14]:
#task 2

ones_array = np.ones((2, 3)) 
zeros_array = np.zeros((3, 2)) 
empty_array = np.empty((2, 2)) 
identity_matrix = np.eye(3) 
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#3
#task 3.1

array_from_list = np.array([1, 2, 3]) 
array_from_tuple = np.array((4, 5, 6)) 
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) 
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [17]:
#task 3.2

arr = np.array([[1, 2, 3], [4, 5, 6]])

zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) # Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[9.34577196e-307 1.18582169e-311 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [4]:
#4.1
#task 1

arr = np.empty((2,2))
arr1 = np.ones((4,2))
new_arr = np.full((2,2), fill_value = 0)
new_arr_zeros = np.zeros_like(arr1, dtype = int)
new_arr_ones = np.ones_like(arr, dtype = int)

new_list = [1,2,3,4,5]
arr_list = np.array(new_list)
print(f"Array with zeros:\n{new_arr_zeros}")
print('\n')
print(f" Array of given shapes and type: \n{new_arr}")
print('\n')
print(f" Array with ones: \n{new_arr_ones}")
print('\n')
print(f"List as array: \n{arr_list}")

Array with zeros:
[[0 0]
 [0 0]
 [0 0]
 [0 0]]


 Array of given shapes and type: 
[[0 0]
 [0 0]]


 Array with ones: 
[[1 1]
 [1 1]]


List as array: 
[1 2 3 4 5]


In [20]:
#task 2

arr_range = np.arange(10, 50) 
print(arr_range)
print('\n')

arr = np.array([0,1,2,3,4,5,6,7,8])
newarr = arr.reshape(3,3)
print(newarr)
print('\n')

arr_id = np.eye(3)
print(arr_id)
print('\n')

arr_rand = np.random.random(30)
print(arr_rand.mean())
print('\n')

arr_min_max = np.random.random((10, 10))
print(f"Min = {arr_min_max.min()}")
print(f"Min = {arr_min_max.max()}")
print('\n')

zero_arr = np.zeros(10)
zero_arr[4] = 1
print(zero_arr)
print('\n')

rev_arr = np.array([1,2,0,0,4,0])
reversed_arr = rev_arr[::1]
print(reversed_arr)
print('\n')

arr_2d = np.ones((5,5))
arr_2d[1:-1, 1:-1] = 0
print(arr_2d)
print('\n')

checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


0.5351579301782781


Min = 0.0046327522250655395
Min = 0.9909479132856965


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


[1 2 0 0 4 0]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [26]:
x = np.array([[1,2], [3,5]])
y = np.array([[5,6], [7,8]])
v = np.array([9,10])
w = np.array([11,12])

arr_add = x + y
print(arr_add)
print('\n')

arr_sub = x - y
print(arr_sub)
print('\n')

arr_mult = x * 3
print(arr_mult)
print('\n')

arr_sqr = x ** 2
print(arr_sqr)
print('\n')


arr_dot_xy = np.dot(v, w)
print(arr_dot_xy)
print('\n')

arr_dot_xv = np.dot(x, v)
print(arr_dot_xv)
print('\n')

arr_dot_xy = np.dot(x,y)
print(arr_dot_xy)
print('\n')

concat_xy = np.concatenate((x,y), axis = 0)
print(concat_xy)
print('\n')

concat_vw = np.column_stack((v,w))
print(concat_vw)

#np.concatenate((x,v), axis = 0) gives -> ValueError: all the input arrays must have the same number of dimensions eroor
# -> Its because you cannot concatenate arrays of different dimensions unless they are reshaped 

[[ 6  8]
 [10 13]]


[[-4 -4]
 [-4 -3]]


[[ 3  6]
 [ 9 15]]


[[ 1  4]
 [ 9 25]]


219


[29 77]


[[19 22]
 [50 58]]


[[1 2]
 [3 5]
 [5 6]
 [7 8]]


[[ 9 11]
 [10 12]]
